Repository dailymotion/vast-client-js, pull requests merged in 2018-07, with the labels that each got.

#227 Fixing 2x docs
  docs/api/vast-client.md
  docs/api/vast-parser.md
  docs/api/vast-tracker.md
Labels: 2.x, documentation

#226 Ad / Ad pod based wrapper resolving
  docs/api/img/adpods.jpg
  docs/api/vast-client.md
  src/parser/parser_utils.js
  src/parser/vast_parser.js
  src/vast_client.js
  test/parser_utils.js
  test/vast_client.js
  test/vastfiles/wrapper-multiple-ads.xml
Labels: 2.x, enhancement

#229 Parsing broken on no ad VAST
  src/parser/vast_parser.js
  test/vast_client.js
Labels: 2.x, fix

#239 Make node engine version more flexible
  package.json
Labels: fix, ready to release
