Repository dailymotion/vast-client-js, pull requests merged in 2018-12, with the labels that each got.

#257 Check if resolveURL is a string.
  src/util/util.js
  test/util.js
Labels: fix, ready to release

#258 Add class reference documentation
  README.md
  docs/api/class-reference.md
  docs/api/vast-client.md
  docs/api/vast-parser.md
Labels: documentation, enhancement

#259 Fix documentation reference links
  README.md
  docs/api/vast-client.md
  docs/api/vast-parser.md
Labels: documentation

#261 Add badges about downloads and license
  README.md
Labels: documentation, enhancement
