Repository dailymotion/vast-client-js, pull requests merged in 2018-05, with the labels that each got.

#216 Update README.md
  README.md
Labels: documentation

#217 Better conditional checks
  src/parser/ad_parser.js
  src/parser/creative_companion_parser.js
  src/parser/creative_linear_parser.js
  src/parser/creative_non_linear_parser.js
  src/parser/vast_parser.js
  src/url_handler.js
  src/util/util.js
  src/vast_tracker.js
Labels: 2.x, enhancement

#214 Sequence persists for wrapper ad
  src/parser.coffee
  test/parser.coffee
Labels: bug

#218 Update potentially insecure old libraries
  package-lock.json
  package.json
  vast-client.js
Labels: 2.x

#219 Merge 1.8.3 into v2.x
  README.md
  vast-client.js
Labels: 2.x
