Repository dailymotion/vast-client-js, pull requests merged in 2018-04, with the labels that each got.

#206 VASTClient API improvements
  src/client.js
  src/index.js
  src/parser/parser.js
  src/parser/parser_utils.js
  src/tracker.js
  src/util/storage.js
  src/util/util.js
  src/vast_client.js
  test/storage.js
  test/tracker.js
  test/util.js
  test/vast_client.js
Labels: 2.x, refactor

#205 VASTParser API improvements
  src/parser/ad_parser.js
  src/parser/creative_companion_parser.js
  src/parser/creative_linear_parser.js
  src/parser/creative_non_linear_parser.js
  src/parser/parser.js
  src/parser/parser_utils.js
  src/parser/vast_parser.js
  src/tracker.js
  src/util/util.js
  src/vast_client.js
  test/tracker.js
  test/vast_parser.js
Labels: 2.x, refactor

#207 VASTTracker API improvements
  src/util/util.js
  src/vast_tracker.js
  test/vast_tracker.js
Labels: 2.x, refactor

#208 API improvements
  src/client.js
  src/index.js
  src/parser/ad_parser.js
  src/parser/creative_companion_parser.js
  src/parser/creative_linear_parser.js
  src/parser/creative_non_linear_parser.js
  src/parser/parser.js
  src/parser/parser_utils.js
  src/parser/vast_parser.js
  src/util/storage.js
  src/util/util.js
  src/vast_client.js
  src/vast_tracker.js
  test/storage.js
  test/util.js
  test/vast_client.js
  test/vast_parser.js
  test/vast_tracker.js
Labels: 2.x

#209 Documentation for 2.0 version
  CONTRIBUTING.md
  README.md
  common-tasks.md
  docs/CONTRIBUTING.md
  docs/RELEASE-TASKS.md
  docs/api/1.x/client.md
  docs/api/1.x/parser.md
  docs/api/1.x/tracker.md
  docs/api/2.0-migration.md
  docs/api/vast-client.md
  docs/api/vast-parser.md
  docs/api/vast-tracker.md
  src/parser/vast_parser.js
  src/util/util.js
  src/vast_tracker.js
  test/util.js
  test/vast_parser.js
Labels: 2.x, documentation

#213 Quartile Fix
  src/vast_tracker.js
  test/vast_tracker.js
Labels: 2.x, bug
