Repository dailymotion/vast-client-js, pull requests merged in 2019-11, with the labels that each got.

#347 Fix node_url_handler bad import
  src/urlhandlers/node_url_handler.js
Labels: 3.0, bug

#346 [tools] Update unsecure dependencies
  package-lock.json
Labels: dependencies, hacktoberfest

#345 [tracker] Autofill ADTYPE, ADSERVINGID & ADCATEGORIES macros when set
  docs/api/vast-tracker.md
  spec/samples/inline_trackers.js
  spec/vast_trackers.spec.js
  src/util/macros.js
  src/vast_tracker.js
Labels: 3.0, enhancement, feature, hacktoberfest

#349 Add npm registry to package.json and .npmrc and fix vulnerabilities
  .npmrc
  package-lock.json
  package.json
Labels: chore

#340 [tool] Add performance test for parsing time
  .eslintignore
  .prettierignore
  bundle_size.js
  package.json
  performance/get_time.js
  performance/parse_time.js
  performance/performance_test.js
  src/urlhandlers/node_url_handler.js
Labels: breaking-change, chore
