Repository dailymotion/vast-client-js, pull requests merged in 2019-02, with the labels that each got.

#276 Fix options.urlHandler assertion
  docs/api/vast-client.md
  docs/api/vast-parser.md
  src/parser/vast_parser.js
Labels: bug, documentation

#277 Require lodash >=4.17.11
  package-lock.json
  package.json
Labels: chore

#274 Replace NodeJS EventEmitter by custom one
  docs/api/event-emitter.md
  docs/api/vast-parser.md
  docs/api/vast-tracker.md
  package-lock.json
  package.json
  rollup.config.js
  src/parser/vast_parser.js
  src/util/event_emitter.js
  src/vast_tracker.js
  test/event_emitter.js
Labels: breaking-change, enhancement
