Repository dailymotion/vast-client-js, pull requests merged in 2019-10, with the labels that each got.

#328 Add tool to compare bundle sizes
  .eslintignore
  .gitignore
  bundleSize.js
  package.json
Labels: 3.0, chore, enhancement

#326 Fix3.0/issue 324
  docs/api/class-reference.md
  package-lock.json
  spec/creative_companion_parser.spec.js
  spec/util.spec.js
  src/parser/ad_parser.js
  src/parser/creative_companion_parser.js
  src/parser/creative_linear_parser.js
  src/parser/creative_non_linear_parser.js
  src/parser/parser_utils.js
  src/util/util.js
  test/vast_parser.js
  test/vastfiles/sample.xml
  test/vastfiles/wrapper-a.xml
  test/vastfiles/wrapper-b.xml
Labels: 3.0, breaking-change, hacktoberfest

#329 Fix3.0/issue 319
  spec/creative_companion_parser.spec.js
  spec/samples/companion_ads.js
  src/companion_ad.js
  src/icon.js
  src/parser/creative_linear_parser.js
  test/vast_parser.js
  test/vastfiles/sample.xml
Labels: 3.0, enhancement, feature, hacktoberfest

#314 [doc] Add code of conduct
  docs/CODE_OF_CONDUCT.md
Labels: chore, documentation, wip

#327 replaced classes with objects
  docs/api/class-reference.md
  src/ad.js
  src/ad_extension.js
  src/ad_verification.js
  src/companion_ad.js
  src/creative/creative.js
  src/creative/creative_companion.js
  src/creative/creative_linear.js
  src/creative/creative_non_linear.js
  src/icon.js
  src/media_file.js
  src/mezzanine.js
  src/non_linear_ad.js
  src/parser/ad_parser.js
  src/parser/creative_companion_parser.js
  src/parser/creative_linear_parser.js
  src/parser/creative_non_linear_parser.js
  src/parser/vast_parser.js
  src/vast_response.js
  src/vast_tracker.js
  test/vast_parser.js
  test/vast_tracker.js
Labels: 3.0, hacktoberfest, refactor

#330 Fix3.0/issue 321
  docs/api/class-reference.md
  spec/creatives_parser.spec.js
  spec/extensions_parser.spec.js
  spec/samples/creatives.js
  spec/samples/extensions.js
  spec/samples/inline_missing_values.js
  spec/vast_verification.spec.js
  src/ad_extension.js
  src/creative/creative.js
  src/extension.js
  src/parser/ad_parser.js
  src/parser/creatives_parser.js
  src/parser/extensions_parser.js
  src/util/requiredValues.js
  test/vast_parser.js
  test/vastfiles/sample.xml
Labels: 3.0, enhancement, feature, hacktoberfest

#313 Migrate event emitter unit tests from mocha to jest
  spec/event_emitter.spec.js
  src/util/event_emitter.js
  test/event_emitter.js
Labels: 3.0, refactor

#335 Fix3.0/issue 320
  docs/api/class-reference.md
  src/closed_caption_file.js
  src/creative/creative_linear.js
  src/interactive_creative_file.js
  src/media_file.js
  src/parser/creative_linear_parser.js
  src/parser/parser_utils.js
  test/vast_parser.js
  test/vastfiles/sample.xml
Labels: 3.0, enhancement, feature, hacktoberfest, refactor

#333 Implement missing VAST 4.1 trackers
  docs/api/vast-tracker.md
  spec/samples/inline_trackers.js
  spec/vast_trackers.spec.js
  src/vast_tracker.js
Labels: 3.0, enhancement, feature

#339 Fix3.0/issue 318
  docs/api/class-reference.md
  spec/samples/inline_missing_values.js
  spec/vast_verification.spec.js
  src/ad_verification.js
  src/parser/ad_parser.js
  src/util/requiredValues.js
  test/vast_parser.js
  test/vastfiles/sample.xml
Labels: 3.0, enhancement, feature, hacktoberfest

#341 Fix3.0/issue 323
  docs/api/class-reference.md
  spec/ad_parser.spec.js
  spec/samples/linear_ads.js
  spec/samples/viewable_impression.js
  src/ad.js
  src/parser/ad_parser.js
Labels: 3.0, enhancement, feature, hacktoberfest

#342 Add missing VAST 4.1 Macros
  docs/api/vast-tracker.md
  spec/samples/inline_trackers.js
  spec/util.spec.js
  spec/vast_trackers.spec.js
  src/util/macros.js
  src/util/util.js
  src/vast_tracker.js
Labels: 3.0, breaking-change, enhancement, feature, hacktoberfest
