Repository dailymotion/vast-client-js, pull requests merged in 2019-01, with the labels that each got.

#265 Clickthrough fallback
  src/vast_tracker.js
  test/vast_tracker.js
Labels: enhancement

#266 NonLinear and Companion ads tracker initialisation
  src/vast_tracker.js
  test/vast_tracker.js
Labels: enhancement, ready to release

#270 Fix naming conflict in Flash and XHR Urlhandlers
  src/urlhandlers/flash_url_handler.js
  src/urlhandlers/xhr_url_handler.js
Labels: fix, ready to release
