Repository dailymotion/vast-client-js, pull requests merged in 2020-12, with the labels that each got.

#374 Make vastTracker.errorWithCode able to replace more than [ERRORCODE] macro
  spec/vast_trackers.spec.js
  src/vast_tracker.js
  test/vast_tracker.js
Labels: enhancement

#375 Fix allowMultipleAds option when resolving wrapper
  docs/api/3.0-migration.md
  docs/api/vast-client.md
  docs/api/vast-parser.md
  spec/vast_parser.spec.js
  src/parser/vast_parser.js
Labels: bug

#377 Issue-376
  docs/api/class-reference.md
  spec/creatives_parser.spec.js
  spec/samples/creatives.js
  spec/samples/inline_trackers.js
  spec/vast_trackers.spec.js
  src/creative/creative.js
  src/parser/creatives_parser.js
  src/vast_tracker.js
  test/vast_parser.js
  test/vastfiles/sample.xml
Labels: breaking-change, enhancement

#381 VastTracker : Updated rollup config for node.js
  rollup.config.js
Labels: bug
