Repository dailymotion/vast-client-js, pull requests merged in 2020-09, with the labels that each got.

#367 Macro track impression
  spec/vast_trackers.spec.js
  src/util/macros.js
  src/vast_tracker.js
  test/vast_tracker.js
Labels: bug

#368 Update dependencies
  package-lock.json
  package.json
  rollup.config.js
Labels: dependencies

#337 [doc] Add 3.0-version migration docs
  README.md
  docs/api/3.0-migration.md
  docs/api/class-reference.md
Labels: 3.0, chore, documentation, hacktoberfest

#361 Improve 3.0-version documentation
  README.md
  docs/api/3.0-migration.md
  docs/api/class-reference.md
  docs/api/event-emitter.md
  docs/api/img/adpods.jpg
  docs/api/vast-client.md
  docs/api/vast-parser.md
  docs/api/vast-tracker.md
  src/vast_tracker.js
Labels: chore, documentation

#369 Update README with 3.0 migration link
  README.md
  docs/api/3.0-migration.md
Labels: chore
