Repository dailymotion/vast-client-js, pull requests merged in 2021-09, with the labels that each got.

#402 [parser] Add bitrate estimation from VAST requests
  docs/api/vast-parser.md
  spec/bitrate.spec.js
  spec/vast_parser.spec.js
  src/parser/bitrate.js
  src/parser/vast_parser.js
Labels: feature

#395 ViewableImpression wrapper + typo doc
  docs/api/class-reference.md
  docs/api/vast-parser.md
  spec/ad_parser.spec.js
  spec/parser_utils.spec.js
  spec/vast_parser.spec.js
  src/ad.js
  src/parser/ad_parser.js
  src/parser/parser_utils.js
  test/vast_parser.js
Labels: enhancement, breaking-change

#401 Updated dependencies because of security issues on vast-client-js
  package-lock.json
  package.json
Labels: dependencies

#403 [parser] Merge correctly adVerification from extension and from its own node
  spec/ad_parser.spec.js
  spec/samples/ad_verification_extension_and_node.js
  src/parser/ad_parser.js
Labels: bug

#407 Prettier 2.0 for VAST-Client
  .eslintrc.js
  bundle_size.js
  jest.config.js
  spec/creative_companion_parser.spec.js
  spec/creatives_parser.spec.js
  spec/event_emitter.spec.js
  spec/extensions_parser.spec.js
  spec/parser_utils.spec.js
  spec/samples/inline_missing_values.js
  spec/samples/inline_trackers.js
  spec/util.spec.js
  spec/utils/utils.js
  spec/vast_client.spec.js
  spec/vast_parser.spec.js
  spec/vast_verification.spec.js
  src/ad.js
  src/ad_verification.js
  src/closed_caption_file.js
  src/companion_ad.js
  src/creative/creative.js
  src/creative/creative_companion.js
  src/creative/creative_linear.js
  src/creative/creative_non_linear.js
  src/extension.js
  src/icon.js
  src/interactive_creative_file.js
  src/media_file.js
  src/mezzanine.js
  src/non_linear_ad.js
  src/parser/bitrate.js
  src/parser/creative_companion_parser.js
  src/parser/creative_linear_parser.js
  src/parser/creative_non_linear_parser.js
  src/parser/creatives_parser.js
  src/parser/extensions_parser.js
  src/parser/parser_utils.js
  src/parser/parser_verification.js
  src/parser/vast_parser.js
  src/url_handler.js
  src/urlhandlers/mock_node_url_handler.js
  src/urlhandlers/node_url_handler.js
  src/urlhandlers/xhr_url_handler.js
  src/util/event_emitter.js
  src/util/macros.js
  src/util/requiredValues.js
  src/util/storage.js
  src/util/util.js
  src/vast_client.js
  src/vast_response.js
  test/vast_parser.js
Labels: chore

#408 [doc] Update doc because Vast-client will be a NPM scoped package @dailymotion/vast-client
  README.md
  package.json
Labels: chore

#411 Update master branch to 3.X to benefit latest fixes
  .eslintrc.js
  README.md
  bundle_size.js
  jest.config.js
  package.json
  spec/creative_companion_parser.spec.js
  spec/creatives_parser.spec.js
  spec/event_emitter.spec.js
  spec/extensions_parser.spec.js
  spec/parser_utils.spec.js
  spec/samples/inline_missing_values.js
  spec/samples/inline_trackers.js
  spec/util.spec.js
  spec/utils/utils.js
  spec/vast_client.spec.js
  spec/vast_parser.spec.js
  spec/vast_verification.spec.js
  src/ad.js
  src/ad_verification.js
  src/closed_caption_file.js
  src/companion_ad.js
  src/creative/creative.js
  src/creative/creative_companion.js
  src/creative/creative_linear.js
  src/creative/creative_non_linear.js
  src/extension.js
  src/icon.js
  src/interactive_creative_file.js
  src/media_file.js
  src/mezzanine.js
  src/non_linear_ad.js
  src/parser/bitrate.js
  src/parser/creative_companion_parser.js
  src/parser/creative_linear_parser.js
  src/parser/creative_non_linear_parser.js
  src/parser/creatives_parser.js
  src/parser/extensions_parser.js
  src/parser/parser_utils.js
  src/parser/parser_verification.js
  src/parser/vast_parser.js
  src/url_handler.js
  src/urlhandlers/mock_node_url_handler.js
  src/urlhandlers/node_url_handler.js
  src/urlhandlers/xhr_url_handler.js
  src/util/event_emitter.js
  src/util/macros.js
  src/util/requiredValues.js
  src/util/storage.js
  src/util/util.js
  src/vast_client.js
  src/vast_response.js
  test/vast_parser.js
Labels: enhancement
