Repository dailymotion/vast-client-js, pull requests merged in 2022-10, with the labels that each got.

#432 Update VASTTracker documentation
  README.md
  docs/api/vast-tracker.md
Labels: documentation, hacktoberfest-accepted

#431 [breaking-change] add safeguards to public methods
  spec/vast_trackers.spec.js
  src/util/event_emitter.js
  src/util/util.js
  src/vast_tracker.js
  test/vast_tracker.js
Labels: breaking-change, hacktoberfest-accepted

#437 Add github action for tests and linting
  .github/workflows/CI.yml
Labels: hacktoberfest, hacktoberfest-accepted
