Repository dailymotion/vast-client-js, pull requests merged in 2022-02, with the labels that each got.

#420 Ad data on resolving events
  docs/api/vast-parser.md
  spec/vast_parser.spec.js
  src/parser/vast_parser.js
Labels: enhancement

#419 Update dependencies
  package-lock.json
  package.json
  performance/parse_time.js
  src/urlhandlers/node_url_handler.js
Labels: chore, dependencies

#421 Release 4.X version
  README.md
  docs/api/class-reference.md
  docs/api/vast-parser.md
  docs/api/vast-tracker.md
  package-lock.json
  package.json
  performance/parse_time.js
  spec/ad_parser.spec.js
  spec/creatives_parser.spec.js
  spec/parser_utils.spec.js
  spec/samples/creatives.js
  spec/samples/inline_trackers.js
  spec/vast_parser.spec.js
  spec/vast_trackers.spec.js
  src/ad.js
  src/creative/creative.js
  src/creative/creative_companion.js
  src/creative/creative_linear.js
  src/creative/creative_non_linear.js
  src/parser/ad_parser.js
  src/parser/creative_companion_parser.js
  src/parser/creative_linear_parser.js
  src/parser/creative_non_linear_parser.js
  src/parser/creatives_parser.js
  src/parser/parser_utils.js
  src/parser/vast_parser.js
  src/urlhandlers/node_url_handler.js
  src/vast_tracker.js
  test/vast_parser.js
  test/vast_tracker.js
  test/vastfiles/sample.xml
Labels: breaking-change
